//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatShareMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutlayLine
    {
        public int olId { get; set; }
        public Nullable<int> oluaId { get; set; }
        public Nullable<decimal> olPayMoney { get; set; }
        public string olRemark { get; set; }
        public Nullable<bool> olDelete { get; set; }
        public Nullable<int> olUpdatedBy { get; set; }
        public Nullable<System.DateTime> olUpdatedDate { get; set; }
        public int oloId { get; set; }
    }
}
