//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatShareMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outlay
    {
        public int oId { get; set; }
        public decimal oTotalMoney { get; set; }
        public int opiId { get; set; }
        public System.DateTime oDate { get; set; }
        public string oRemark { get; set; }
        public Nullable<bool> oDeleted { get; set; }
        public int oUpdatedBy { get; set; }
        public System.DateTime oUpdatedDate { get; set; }
        public Nullable<int> ouaId { get; set; }
    }
}
