//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatShareMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayItem
    {
        public int piId { get; set; }
        public string piName { get; set; }
        public string piRemark { get; set; }
        public Nullable<bool> piDeleted { get; set; }
        public Nullable<int> piUpdatedBy { get; set; }
        public Nullable<System.DateTime> piUpdatedDate { get; set; }
    }
}
