//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatShareMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Settlement
    {
        public int sId { get; set; }
        public Nullable<System.DateTime> sStartDate { get; set; }
        public Nullable<System.DateTime> sEndDate { get; set; }
        public Nullable<decimal> sTotalCost { get; set; }
        public Nullable<bool> sDeleted { get; set; }
        public Nullable<int> sUpdatedBy { get; set; }
        public Nullable<System.DateTime> sUpdatedDate { get; set; }
    }
}
