//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatShareMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettlementLine
    {
        public int slId { get; set; }
        public Nullable<int> slsId { get; set; }
        public Nullable<int> sluaId { get; set; }
        public Nullable<decimal> sActuallyPay { get; set; }
        public Nullable<decimal> sPayable { get; set; }
        public Nullable<decimal> sBalance { get; set; }
        public Nullable<bool> sDeleted { get; set; }
    }
}
