//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlatShareMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int uaId { get; set; }
        public string uaUserName { get; set; }
        public string uaLoginName { get; set; }
        public string uaPassword { get; set; }
        public string uaTelephone { get; set; }
        public string uaRemark { get; set; }
        public Nullable<bool> uaDeleted { get; set; }
        public int uaUpdatedBy { get; set; }
        public System.DateTime uaUpdatedDate { get; set; }
        public Nullable<bool> uaEnable { get; set; }
    }
}
